### ISSUE TITLE
아이콘 배경 지우기

### ISSUE THREAD

**Issue by Dev-james1112** [Team-Centillion/Main_Page#8]
아이콘 배경 공백으로 전환 바람 다운받을때 뒤를 지우거나
https://remove.bg 에서 바꾸길 바람

담당자: @Paul0309

**Comment by Dev-james1112** [comment]
asdf

**Comment by Paul0309** [comment]
![Uploading icon.png…]()

**Comment by Paul0309** [comment]
![icon](https://user-images.githubusercontent.com/94342774/164978462-280d709b-e869-4df4-b8dc-0edd59b3a8f5.png)
